{
 "title": "Dataflow",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PROJECT_ID", "query": "$projectId" }
  ]
 },
 "panels": [
  { "title": "Dataflow Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job failed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/is_failed",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Job failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "editorMode": "visual",
      "filters": [
       "resource.label.job_name",
       "=",
       "${jobname}"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/is_failed",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Elapsed Time",
   "type": "gauge",
   "description": "Duration that the current run of this pipeline has been in the Running state so far, in seconds. When a run completes, this stays at the duration of that run until the next run starts.",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/elapsed_time",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total PD usage Time",
   "type": "gauge",
   "description": "The total GB seconds for all persistent disk used by all workers associated with this Dataflow job.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "metric.label.storage_type" ],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/total_pd_usage_time",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Thread Time",
   "type": "timeseries",
   "description": "Estimated time in milliseconds spent running in the function of the ptransform totaled across threads on all workers of the job.",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "metric.label.ptransform" ],
      "metricKind": "DELTA",
      "metricType": "dataflow.googleapis.com/job/thread_time",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk Space capacity",
   "type": "gauge",
   "description": "The amount of persistent disk currently being allocated to all workers associated with this Dataflow job.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "metric.label.storage_type" ],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/disk_space_capacity",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pub/Sub Pull Request Latencies",
   "type": "timeseries",
   "description": "Pub/Sub Pull request latencies from PubsubIO.Read in Dataflow jobs. For Streaming Engine, this metric is deprecated. See the \"Using the Dataflow monitoring interface\" page for upcoming changes.",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "resource.label.job_name" ],
      "metricKind": "DELTA",
      "metricType": "dataflow.googleapis.com/job/pubsub/read_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Total streaming data processed",
   "type": "gauge",
   "description": "The total bytes of streaming data processed by this Dataflow job.",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/total_streaming_data_processed",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total shuffle data processed",
   "type": "gauge",
   "description": "The total bytes of shuffle data processed by this Dataflow job",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/total_shuffle_data_processed",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "CPU / Memory ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "AND",
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "${compute}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Total vCPU time",
   "type": "gauge",
   "description": "The total vCPU seconds used by this Dataflow job.",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/total_vcpu_time",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Current number of vCPUs in use",
   "type": "gauge",
   "description": "The number of vCPUs currently being used by this Dataflow job. This is the current number of workers times the number of vCPUs per worker.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/current_num_vcpus",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "gauge",
   "description": "Estimated memory used vs memory limit in bytes for the worker which uses the most memory in this Dataflow job. This chart can be used for debugging OOM (Out of Memory) issues.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Max worker memory Usage",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "metric.label.state",
       "!=",
       "free"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/guest/memory/bytes_used",
      "perSeriesAligner": "ALIGN_MAX",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "Estimated memory used vs memory limit in bytes for the worker which uses the most memory in this Dataflow job. This chart can be used for debugging OOM (Out of Memory) issues.",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Max worker memory Usage",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "metric.label.state",
       "!=",
       "free",
       "AND",
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/guest/memory/bytes_used",
      "perSeriesAligner": "ALIGN_MAX",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Max worker memory Capacity",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/guest/memory/bytes_used",
      "perSeriesAligner": "ALIGN_MAX",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Memory capacity",
   "type": "gauge",
   "description": "The amount of memory currently being allocated to all workers associated with this Dataflow job.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "dataflow_job"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/memory_capacity",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total memory usage Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "total_memory_usage_time ",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/total_memory_usage_time",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  { "title": "Overview Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "The number of elements produced by each PTransform",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "element/s" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "metric.label.ptransform" ],
      "metricKind": "DELTA",
      "metricType": "dataflow.googleapis.com/job/elements_produced_count",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "System lag",
   "type": "gauge",
   "description": "The current maximum duration that an item of data has been processing or awaiting processing, in seconds.",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "resource.label.job_name" ],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/system_lag",
      "perSeriesAligner": "ALIGN_MAX",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Data Freshness",
   "type": "timeseries",
   "description": "The age (time since event timestamp) up to which all data has been processed by the pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "dataflow.googleapis.com/job/data_watermark_age",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Worker Error Log count",
   "type": "timeseries",
   "description": "Number of log entries that contributed to user-defined metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "+1800s",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "AND",
       "metric.label.severity",
       "=",
       "ERROR",
       "AND",
       "metric.label.log",
       "=",
       "dataflow.googleapis.com/worker"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/log_entry_count",
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "${projectId}",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}