dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: false
     editable: true
     options:
       path: /var/lib/grafana/dashboards/default

adminUser: admin
adminPassword: admin

dashboards:
  default:
    custom-dashboard:
      file: dashboards/dataflow-dashboard.json